# Generated by Django 5.0.6 on 2024-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
