# Generated by Django 5.0.6 on 2024-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_todo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
