# Generated by Django 5.0.6 on 2024-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_alter_todo_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
    ]
