# Generated by Django 5.0.6 on 2024-10-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0005_alter_todo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
