# Generated by Django 5.0.6 on 2024-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
